import os

MPCA_DIR = r"S:\B.Tech Data Science Notes\Semester 3\MPCA"

unit2_dir = os.path.join(MPCA_DIR, "Module 2", "Module_2_QA")
unit3_dir = os.path.join(MPCA_DIR, "Module 3", "Module_3_QA")

os.makedirs(unit2_dir, exist_ok=True)
os.makedirs(unit3_dir, exist_ok=True)

# ==========================================================================
# UNIT 2 FILES
# ==========================================================================

u2_2m = """# 2-Mark Questions & Answers — MPCA Unit 2: Processor Organization & Architecture

---

### Q1. Define pipelining.

**Pipelining** is an instruction execution technique where multiple instructions are overlapped in execution across independent hardware stages (Fetch, Decode, Execute, Memory, Write-back), increasing instruction throughput without increasing individual execution time.

---

### Q2. What is a pipeline hazard?

A **Pipeline Hazard** is any condition or situation (such as structural resource contention, data dependencies, or branch instructions) that prevents the next instruction in the pipeline stream from executing in its designated clock cycle.

---

### Q3. List Flynn's classification of computer architecture.

1. **SISD:** Single Instruction Stream, Single Data Stream.
2. **SIMD:** Single Instruction Stream, Multiple Data Streams.
3. **MISD:** Multiple Instruction Streams, Single Data Stream.
4. **MIMD:** Multiple Instruction Streams, Multiple Data Streams.

---

### Q4. What is microprogrammed control unit?

A **Microprogrammed Control Unit** is a control unit design where control signals are generated by reading microinstructions (stored in a Control Memory ROM) sequentially, rather than using fixed hardwired logic gates.

---

### Q5. Define instruction cycle.

An **Instruction Cycle** (or Fetch-Decode-Execute cycle) is the sequence of operations performed by the CPU to execute a single machine instruction. It consists of the **Fetch phase**, **Decode phase**, **Effective Address calculation phase**, **Execute phase**, and **Interrupt service check phase**.
"""

u2_3m = """# 3-Mark Questions & Answers — MPCA Unit 2: Processor Organization & Architecture

---

### Q1. Explain the basic instruction cycle with interrupt processing.

```
+---------------+     +----------------+     +-----------------+
| FETCH         | --> | DECODE         | --> | EXECUTE         |
| Instruction   |     | Instruction    |     | Operation       |
+---------------+     +----------------+     +-----------------+
        ^                                             |
        |               [Interrupt Pending?]          v
        +------------------ NO <--- [CHECK INTERRUPT]
                                         | YES
                                         v
                              +--------------------+
                              | SAVE CONTEXT (PC)  |
                              | & JUMP TO ISR      |
                              +--------------------+
```
- **Fetch:** Load instruction from memory (`PC` -> `MAR` -> `RAM` -> `IR`).
- **Decode:** Decode opcode and fetch required operands.
- **Execute:** Perform operation in ALU.
- **Interrupt Check:** Check if an hardware/software interrupt flag is set; if yes, push context to stack and jump to Interrupt Service Routine (ISR).

---

### Q2. Differentiate between hardwired and microprogrammed control unit.

| Feature | Hardwired Control Unit | Microprogrammed Control Unit |
| :--- | :--- | :--- |
| **Implementation** | Fixed logic gates, flip-flops, decoders. | Microcode software stored in Control Memory (ROM). |
| **Speed** | Very Fast (hardware gate speeds). | Slower (requires ROM access cycles). |
| **Flexibility / Modifiability** | Rigid; hard to modify or update. | Flexible; easy to update microcode. |
| **Cost & Design** | Complex design, costly for complex ISA. | Systematic design, cheaper for CISC. |

---

### Q3. Explain types of pipeline hazards (structural, data, control) briefly.

1. **Structural Hazard (Resource Conflict):** Occurs when two instructions in different stages attempt to access the same physical hardware resource simultaneously (e.g., single memory port for instruction fetch and data read).
2. **Data Hazard (Data Dependency):** Occurs when an instruction depends on the result of a previous instruction that has not yet completed execution (RAW, WAR, WAW hazards).
3. **Control Hazard (Branch Hazard):** Occurs due to conditional or unconditional branch instructions that alter the sequential flow of the Program Counter (`PC`).

---

### Q4. Explain Flynn's classification (SISD, SIMD, MISD, MIMD) with examples.

1. **SISD (Single Instruction, Single Data):** Classic single-core processor executing one stream of scalar data (e.g., Intel 8086, traditional single-core CPUs).
2. **SIMD (Single Instruction, Multiple Data):** One instruction operates on vector/matrix array elements concurrently (e.g., GPUs, Intel AVX/SSE).
3. **MISD (Multiple Instruction, Single Data):** Multiple processors execute different instructions on the same data stream (e.g., Space Shuttle fault-tolerant flight control).
4. **MIMD (Multiple Instruction, Multiple Data):** Independent processors executing different instructions on independent data streams (e.g., Intel Core i9 multi-core CPUs, supercomputers).

---

### Q5. What are micro-operations? Give examples.

**Micro-operations** are elementary functional operations executed by CPU hardware during a single clock pulse to perform register transfers, ALU calculations, or bus reads.
- **Examples:**
  1. `MAR <- PC` (Transfer Program Counter to Memory Address Register)
  2. `DR <- M[MAR]` (Fetch memory contents into Data Register)
  3. `PC <- PC + 1` (Increment Program Counter)
  4. `AC <- AC + DR` (Add Data Register to Accumulator)
"""

u2_5m = """# 5-Mark Questions & Answers — MPCA Unit 2: Processor Organization & Architecture

---

### Q1. Explain hardwired control unit design with a block diagram.

```
                +---------------------------------------+
                |  INSTRUCTION REGISTER (IR) (Opcode)  |
                +---------------------------------------+
                                   |
                                   v
+---------------+        +--------------------+        +---------------------+
| CLOCK PULSES  | -----> | INSTRUCTION DECODER| <----- | SEQUENCE COUNTER    |
+---------------+        +--------------------+        | & FLAG CONDITIONERS |
                                   |                   +---------------------+
                                   v
                        +----------------------+
                        | CONTROL LOGIC GATES  |
                        +----------------------+
                                   |
                                   v
                     System Control Signals (Read, Write, ALU Control)
```

1. **Opcode Decoder:** Decodes machine instruction opcode into active signal lines.
2. **Sequence Counter:** Generates timing signals ($T_0, T_1, T_2, \dots$) for sequential step execution.
3. **Control Logic Combinational Circuit:** Logic gates synthesize control signals ($C_{\text{read}}, C_{\text{write}}, \text{ALU}_{\text{add}}$) dynamically based on opcode and condition flags.
4. **Pros & Cons:** Ultra-high speed execution, but extremely difficult to modify or debug once fabricated.

---

### Q2. Explain microprogrammed control unit with microinstruction sequencing and execution.

```
+------------------+     +------------------------+     +------------------------+
| NEXT ADDRESS     | --> | CONTROL MEMORY (ROM)   | --> | CONTROL ADDRESS        |
| GENERATOR        |     | (Microprogram Storage) |     | REGISTER (CAR)         |
+------------------+     +------------------------+     +------------------------+
         ^                                                          |
         |                   +------------------+                   v
         +------------------ | CONTROL DATA     | --------> Control Signals
                             | REGISTER (CDR)   |           to CPU Hardware
                             +------------------+
```

1. **Control Memory (ROM):** Holds sequences of microinstructions (microprogram) for every machine instruction opcode.
2. **Control Address Register (CAR):** Contains the memory address of the next microinstruction to fetch.
3. **Control Data Register (CDR) / Control Buffer:** Holds the currently fetched microinstruction containing control signals and next-address fields.
4. **Sequencing & Execution:**
   - **Sequencer Logic:** Determines whether to increment `CAR` or branch to a target microinstruction address based on condition flags.

---

### Q3. Explain instruction pipelining with a diagram and discuss speedup achieved.

```
Clock Cycle  :  C1    C2    C3    C4    C5    C6    C7
------------------------------------------------------
Instr 1      : [ IF ][ ID ][ EX ][ MEM ][ WB ]
Instr 2      :       [ IF ][ ID ][ EX  ][ MEM ][ WB ]
Instr 3      :             [ IF ][ ID  ][ EX  ][ MEM ][ WB ]
```

#### Speedup Calculation
For an $k$-stage pipeline executing $n$ instructions:
- **Non-Pipelined Time ($T_{\text{non-pipe}}$):** $n \times k \times \tau$
- **Pipelined Time ($T_{\text{pipe}}$):** $(k + n - 1) \times \tau$
- **Speedup ($S$):**
  $$S = \frac{T_{\text{non-pipe}}}{T_{\text{pipe}}} = \frac{n \cdot k \cdot \tau}{(k + n - 1) \cdot \tau}$$
- For a large number of instructions ($n \to \infty$):
  $$S_{\text{max}} = k \quad (\text{Equal to number of pipeline stages})$$

---

### Q4. Explain different types of pipeline hazards and techniques to overcome them.

1. **Structural Hazards (Hardware Conflicts):**
   - *Cause:* Multiple stages attempting simultaneous access to a shared resource.
   - *Solution:* Duplicate resources (e.g., separate Instruction Cache and Data Cache).
2. **Data Hazards (Data Dependencies):**
   - *Types:* Read-After-Write (RAW), Write-After-Read (WAR), Write-After-Write (WAW).
   - *Solution:* **Data Forwarding / Bypassing** (routing ALU output directly back to ALU input), or inserting **Pipeline Stalls (NAPs/Bubbles)**.
3. **Control Hazards (Branch Dependencies):**
   - *Cause:* Conditional branch decisions delaying instruction fetch stream.
   - *Solution:* **Branch Prediction** (Static/Dynamic), **Branch Target Buffers (BTB)**, or **Delayed Branching**.

---

### Q5. Describe Flynn's classification of parallel processing architectures in detail with diagrams.

```
       +----------------------------------+----------------------------------+
       |            SINGLE DATA           |          MULTIPLE DATA           |
+------+----------------------------------+----------------------------------+
|SINGLE|  SISD (Single Inst, Single Data)  |  SIMD (Single Inst, Multiple Data)|
|INST  |  [CU] -> [PE] -> [Memory]        |  [CU] -> [PE1, PE2, PE3]         |
+------+----------------------------------+----------------------------------+
|MULTI |  MISD (Multi Inst, Single Data)  |  MIMD (Multi Inst, Multiple Data)|
|INST  |  [CU1, CU2] -> [Single Data]     |  [CU1, CU2] -> [PE1, PE2]        |
+------+----------------------------------+----------------------------------+
```

1. **SISD:** Standard uniprocessor system.
2. **SIMD:** Vector processors, GPUs, SIMD extensions (AVX-512) for parallel array calculations.
3. **MISD:** Specialized fault-tolerant computers (redundant processing on identical data).
4. **MIMD:** Multi-core processors, distributed computing clusters, supercomputers.

---

### Q6. Explain the basic instruction cycle along with interrupt processing in detail.

1. **Fetch Phase:** CPU fetches opcode byte from memory location specified by `PC` into `IR`. Program Counter is incremented (`PC = PC + 1`).
2. **Decode Phase:** Control unit decodes opcode to determine operation and operand locations.
3. **Operand Fetch Phase:** Effective address is calculated and operands loaded into data registers.
4. **Execute Phase:** ALU performs arithmetic or logical operation.
5. **Interrupt Processing Phase:**
   - At the end of every instruction cycle, the CPU polls the Interrupt request line.
   - If an interrupt is active and enabled:
     1. Current `PC` and `FLAGS` are pushed onto the Stack.
     2. Interrupt vector address is loaded into `PC`.
     3. Execution jumps to the Interrupt Service Routine (ISR).
     4. `IRET` pops saved state back to resume original program execution.
"""

u2_10m = """# 10-Mark Questions & Answers — MPCA Unit 2: Processor Organization & Architecture

---

### Q1. Explain hardwired and microprogrammed control units in detail with block diagrams, and compare their advantages/disadvantages.

#### 1. Hardwired Control Unit Architecture

```
                       +-------------------------------+
                       | INSTRUCTION REGISTER (IR)     |
                       +-------------------------------+
                                       |
                                       v
+------------------+         +-------------------+         +-----------------------+
| SYSTEM CLOCK     | ------->| OPCODE DECODER    | <-------| SEQUENCE COUNTER      |
+------------------+         +-------------------+         | & CONDITION FLAGS     |
                                       |                   +-----------------------+
                                       v
                            +----------------------+
                            | COMBINATIONAL LOGIC  |
                            | MATRIX (Gates)       |
                            +----------------------+
                                       |
                                       v
                            Control Signals (Read/Write/ALU)
```

#### 2. Microprogrammed Control Unit Architecture

```
+---------------------+     +-----------------------+     +----------------------+
| CONTROL ADDRESS     | --> | CONTROL MEMORY (ROM)  | --> | CONTROL DATA REGISTER|
| REGISTER (CAR)      |     | (Microcode Storage)   |     | (CDR / Microinst)    |
+---------------------+     +-----------------------+     +----------------------+
           ^                                                         |
           |                  +---------------------+                v
           +----------------- | SEQUENCER LOGIC     | <---- Control Signals to Hardware
                              +---------------------+
```

#### 3. Comprehensive Comparison Table

| Feature | Hardwired Control Unit | Microprogrammed Control Unit |
| :--- | :--- | :--- |
| **Logic Implementation** | Fixed combinational logic gates & flip-flops. | Microcode software stored in Control Memory ROM. |
| **Execution Speed** | Extremely fast (limited only by hardware gate delay). | Slower (dependent on Control ROM fetch cycle time). |
| **Flexibility** | Rigid. Modifications require hardware redesign. | Highly flexible. Upgraded by updating Control ROM microcode. |
| **Instruction Set Type** | Best suited for RISC architectures. | Best suited for complex CISC architectures. |
| **Cost & Complexity** | High cost and design complexity for large ISAs. | Systematic design, lower cost for complex ISAs. |
| **Debugging & Maintenance**| Difficult to debug and maintain. | Easier to debug and maintain. |

---

### Q2. Explain instruction pipelining in detail. Discuss structural, data, and control hazards with examples and methods to resolve each (forwarding, stalling, branch prediction).

#### 1. 5-Stage RISC Instruction Pipeline

```
Stage 1: IF  (Instruction Fetch)   -> Read instruction from I-Cache.
Stage 2: ID  (Instruction Decode)  -> Read registers & decode instruction.
Stage 3: EX  (Execution / ALU)     -> Execute ALU operation or calculate memory address.
Stage 4: MEM (Memory Access)       -> Read/Write data from D-Cache.
Stage 5: WB  (Write Back)          -> Write result back into destination register.
```

#### 2. Pipeline Hazards & Resolution Strategies

1. **Structural Hazards (Resource Contention):**
   - *Example:* A single-port memory attempting simultaneous instruction fetch (`IF`) and data memory read (`MEM`).
   - *Resolution:* Implement separate Instruction and Data Caches (Harvard Architecture model).

2. **Data Hazards (Data Dependencies):**
   - *Example (RAW Hazard):*
     ```assembly
     ADD R1, R2, R3   ; R1 written in WB stage
     SUB R4, R1, R5   ; R1 read in ID stage (Hazard!)
     ```
   - *Resolution Methods:*
     - **Data Forwarding (Bypassing):** Connect the ALU output of `EX` stage directly back to `EX` stage input via a multiplexer, eliminating wait cycles.
     - **Pipeline Stalling (NAPs / Bubbles):** Insert hardware stall cycles until data is written back.

3. **Control Hazards (Branch Dependencies):**
   - *Example:* Conditional branch instruction `BEQ R1, R2, Target` alters sequential instruction fetching.
   - *Resolution Methods:*
     - **Static/Dynamic Branch Prediction:** Predict whether branch is taken or not taken (Branch History Table).
     - **Branch Target Buffer (BTB):** Cache branch target addresses for instant fetching.

---

### Q3. Explain the basic instruction cycle with interrupt processing in detail, including the fetch-decode-execute cycle and interrupt handling mechanism.

```
                      +-------------------+
                      |   FETCH STAGE     |
                      |   MAR <- PC       |
                      |   MDR <- M[MAR]   |
                      |   IR  <- MDR      |
                      |   PC  <- PC + 1   |
                      +-------------------+
                                |
                                v
                      +-------------------+
                      |   DECODE STAGE    |
                      |   Decode Opcode   |
                      |   Fetch Operands  |
                      +-------------------+
                                |
                                v
                      +-------------------+
                      |   EXECUTE STAGE   |
                      |   ALU Compute     |
                      |   Write Result    |
                      +-------------------+
                                |
                                v
                      +-------------------+
                      | INTERRUPT CHECK?  |
                      +-------------------+
                         /             \
                   YES  /               \ NO
                       v                 v
            +--------------------+    Next Cycle (Fetch)
            | Push PC & FLAGS    |
            | Load ISR Address   |
            +--------------------+
```

#### Detailed Phase Breakdown
1. **Fetch:** CPU transfers `PC` to `MAR`, issues memory read signal, loads fetched byte into `IR`, and increments `PC`.
2. **Decode:** Opcode is decoded; operand addresses are calculated.
3. **Execute:** ALU executes mathematical or logic operation.
4. **Interrupt Servicing Mechanism:**
   - At the conclusion of execution, CPU checks interrupt line status.
   - If an interrupt request is active:
     1. Current `FLAGS`, `CS`, and `IP` are pushed onto the Stack.
     2. Interrupt Enable (`IF`) and Trap (`TF`) flags are cleared.
     3. Interrupt vector address is loaded into `CS:IP`.
     4. Control transfers to ISR; ends with `IRET` restoring original context.

---

### Q4. Describe microinstruction sequencing and execution techniques (in microprogrammed control) along with a suitable example of microinstruction format.

#### 1. Microinstruction Format Structure

```
+-------------------+--------------------+--------------------+--------------------+
| CONTROL FIELD     | CONDITION FIELD    | BRANCH FIELD       | ADDRESS FIELD      |
| (Control Signals) | (Status Flags Test)| (Jump Condition)   | (Next Micro-Addr)  |
| (16-32 bits)      | (2-4 bits)         | (2-3 bits)         | (8-12 bits)        |
+-------------------+--------------------+--------------------+--------------------+
```

#### 2. Microinstruction Sequencing Techniques

1. **Two-Address Fields:**
   - Microinstruction contains two explicit address fields: Next address if condition is TRUE, and Next address if condition is FALSE.
2. **Single-Address Field with Increment:**
   - Microinstruction contains one address field used for branching; if no branch occurs, `CAR` is automatically incremented (`CAR = CAR + 1`).
3. **Variable Format / Opcode Mapping:**
   - Opcode bytes from machine instruction are mapped via a PLA/ROM lookup table directly into the starting microinstruction address in Control ROM.

---

### Q5. Explain Flynn's classification of computer architectures in detail with block diagrams and real-world examples for each category.

```
1. SISD Architecture                  2. SIMD Architecture
   +----+     +----+     +------+        +----+     +-----+ -> [PE1] -> [Mem1]
   | CU | --> | PE | --> | Mem  |        | CU | --> | Bus | -> [PE2] -> [Mem2]
   +----+     +----+     +------+        +----+     +-----+ -> [PE3] -> [Mem3]

3. MISD Architecture                  4. MIMD Architecture
   +-----+     +-----+                   +-----+     +-----+     +------+
   | CU1 | --> | PE1 | -\                | CU1 | --> | PE1 | --> | Mem1 |
   +-----+     +-----+   \               +-----+     +-----+     +------+
                          +-> [Shared]
   +-----+     +-----+   /               +-----+     +-----+     +------+
   | CU2 | --> | PE2 | -/                | CU2 | --> | PE2 | --> | Mem2 |
   +-----+     +-----+                   +-----+     +-----+     +------+
```

1. **SISD (Single Instruction, Single Data):** Standard uniprocessor architecture executing sequential instructions on a single scalar data stream.
   - *Example:* Intel 8086, early Pentium processors.
2. **SIMD (Single Instruction, Multiple Data):** Single control unit dispatches one instruction to multiple Processing Elements (PEs) operating concurrently on distinct data vector streams.
   - *Example:* Nvidia GPUs (CUDA cores), Intel AVX-512 extensions.
3. **MISD (Multiple Instruction, Single Data):** Multiple autonomous control units execute distinct instructions on a single shared data stream.
   - *Example:* Spacecraft redundant flight computers.
4. **MIMD (Multiple Instruction, Multiple Data):** Independent processors execute autonomous instruction streams on independent data streams.
   - *Example:* Multi-core CPUs (Intel Core i9, AMD EPYC), Supercomputer clusters.
"""

# Write Unit 2 files
with open(os.path.join(unit2_dir, "2M.md"), "w", encoding="utf-8") as f: f.write(u2_2m)
with open(os.path.join(unit2_dir, "3M.md"), "w", encoding="utf-8") as f: f.write(u2_3m)
with open(os.path.join(unit2_dir, "5M.md"), "w", encoding="utf-8") as f: f.write(u2_5m)
with open(os.path.join(unit2_dir, "10M.md"), "w", encoding="utf-8") as f: f.write(u2_10m)

print("Created Unit 2 QA Files!")
