import os

MPCA_DIR = r"S:\B.Tech Data Science Notes\Semester 3\MPCA"
unit3_dir = os.path.join(MPCA_DIR, "Module 3", "Module_3_QA")
os.makedirs(unit3_dir, exist_ok=True)

# ==========================================================================
# UNIT 3 FILES
# ==========================================================================

u3_2m = """# 2-Mark Questions & Answers — MPCA Unit 3: The Intel Microprocessor 8086 Architecture

---

### Q1. List the functional units of the 8086 microprocessor.

The 8086 CPU is divided into two independent functional units:
1. **Bus Interface Unit (BIU):** Manages instruction prefetching, memory bus communication, segment registers, and physical address generation.
2. **Execution Unit (EU):** Decodes micro-instructions, executes arithmetic/logical operations in ALU, and manages general-purpose registers and flags.

---

### Q2. What is memory segmentation in 8086?

**Memory Segmentation** is a technique that divides the 1MB physical memory space into 64KB logical blocks called segments (Code Segment, Data Segment, Stack Segment, Extra Segment). It allows a 16-bit processor to address 20-bit physical addresses using segment base registers and offset registers.

---

### Q3. Define minimum mode and maximum mode of 8086.

- **Minimum Mode ($\text{MN}/\overline{\text{MX}} = 1$):** Single-processor system mode where 8086 generates all bus control signals (`RD`, `WR`, `ALE`, `M/IO`) directly.
- **Maximum Mode ($\text{MN}/\overline{\text{MX}} = 0$):** Multi-processor system mode where bus control signals are generated by an external Bus Controller chip (Intel 8288).

---

### Q4. What is the purpose of demultiplexing the address/data bus?

The 8086 uses multiplexed pins $\text{AD}_0 - \text{AD}_{15}$ to save physical pin count. **Demultiplexing** separates the 20-bit memory address from 16-bit data using octal latches (74LS373) driven by the Address Latch Enable (`ALE`) signal.

---

### Q5. State the size of the 8086 instruction queue.

The 8086 Bus Interface Unit (BIU) contains a **6-byte Instruction Queue** that prefetches instruction bytes sequentially from memory when the EU is busy, enabling instruction pipelined prefetching.
"""

u3_3m = """# 3-Mark Questions & Answers — MPCA Unit 3: The Intel Microprocessor 8086 Architecture

---

### Q1. Draw and explain the functional pin diagram of 8086 (any 6-8 important pins).

1. **$\text{AD}_0 - \text{AD}_{15}$ (Pins 2-16, 39):** Multiplexed Address/Data lines carrying 16-bit data or lower 16-bit memory address.
2. **$\text{A}_{16}/\text{S}_3 - \text{A}_{19}/\text{S}_6$ (Pins 35-38):** Multiplexed upper 4-bit address lines and status signals.
3. **$\text{ALE}$ (Address Latch Enable):** High pulse indicating valid address is present on multiplexed bus.
4. **$\text{RD}$ / $\text{WR}$:** Memory/IO Read and Write control output signals.
5. **$\text{MN}/\overline{\text{MX}}$ (Pin 33):** Configures CPU for Minimum Mode (+5V) or Maximum Mode (GND).
6. **$\text{RESET}$ (Pin 21):** Resets CPU; sets `CS = FFFFH`, `IP = 0000H`.

---

### Q2. Explain memory segmentation in 8086 with a diagram.

```
1 MB Memory Space (00000H to FFFFFH)
+------------------------------------+ FFFFFH
|      UNMAPPED MEMORY SPACE         |
+------------------------------------+
|  EXTRA SEGMENT (ES)     (64 KB)    | <- ES:DI
+------------------------------------+
|  STACK SEGMENT (SS)     (64 KB)    | <- SS:SP/BP
+------------------------------------+
|  DATA SEGMENT (DS)      (64 KB)    | <- DS:BX/SI
+------------------------------------+
|  CODE SEGMENT (CS)      (64 KB)    | <- CS:IP
+------------------------------------+ 00000H
```
- Total Physical Address Space = $2^{20} = 1\text{ MB}$.
- Divided into 4 active 64KB logical segments: **CS** (Code), **DS** (Data), **SS** (Stack), **ES** (Extra).

---

### Q3. Explain the concept of banking (memory banking) in 8086.

```
         1MB PHYSICAL MEMORY
       /                     \
  EVEN BANK (Even Bytes)     ODD BANK (Odd Bytes)
  512 KB (D0 - D7)           512 KB (D8 - D15)
  Connected to BHE=1         Connected to BHE=0
```
- Memory is split into two 512KB banks:
  - **Even Bank (Lower Bank):** Contains even byte addresses ($00000\text{H}, 00002\text{H}, \dots$), driven by $A_0 = 0$.
  - **Odd Bank (Upper Bank):** Contains odd byte addresses ($00001\text{H}, 00003\text{H}, \dots$), driven by $\overline{\text{BHE}} = 0$.
- Enables fetching 16-bit word data in a single memory cycle when aligned on an even address.

---

### Q4. Differentiate between minimum mode and maximum mode operation of 8086.

| Feature | Minimum Mode | Maximum Mode |
| :--- | :--- | :--- |
| **Pin Setup** | Pin 33 ($\text{MN}/\overline{\text{MX}}$) connected to $+5\text{V}$. | Pin 33 ($\text{MN}/\overline{\text{MX}}$) connected to $\text{GND}$. |
| **System Architecture**| Single CPU processor system. | Multi-processor / Co-processor system (8087 FPU, 8089 IOP). |
| **Control Generator** | 8086 directly outputs `RD`, `WR`, `ALE`, `M/IO`. | External 8288 Bus Controller decodes status pins $\bar{S}_0, \bar{S}_1, \bar{S}_2$. |

---

### Q5. Explain the need for demultiplexing the address/data bus in 8086.

1. Pins $\text{AD}_0 - \text{AD}_{15}$ carry memory addresses during the first clock cycle ($T_1$) and data during $T_2, T_3, T_4$.
2. Without demultiplexing, memory chips would lose the target address when data values are placed on the pins during $T_2$.
3. Latches (74LS373) latch the address when `ALE = 1`, preserving a stable 20-bit address throughout the memory cycle.
"""

u3_5m = """# 5-Mark Questions & Answers — MPCA Unit 3: The Intel Microprocessor 8086 Architecture

---

### Q1. Explain the internal architecture of 8086 (BIU and EU) with a neat diagram.

```
+-------------------------------------------------------------------------+
|                        BUS INTERFACE UNIT (BIU)                         |
|                                                                         |
|   Segment Registers: [ CS ][ DS ][ SS ][ ES ]    IP: [ Instruction Ptr ]|
|                                  |                                      |
|                                  v                                      |
|                        20-Bit Adder (Physical Addr)                     |
|                                  |                                      |
|                                  v                                      |
|                 6-Byte Instruction Stream Queue [Q1|Q2|Q3|Q4|Q5|Q6]      |
+----------------------------------|--------------------------------------+
                                   | Internal Bus
+----------------------------------v--------------------------------------+
|                           EXECUTION UNIT (EU)                           |
|                                                                         |
|   General Registers:  [ AH | AL ] [ BH | BL ] [ CH | CL ] [ DH | DL ]   |
|   Pointers & Indexes: [ SP ] [ BP ] [ SI ] [ DI ]                       |
|                                                                         |
|   Control Logic <---> 16-Bit ALU <---> Status & Control Flags (16-bit)   |
+-------------------------------------------------------------------------+
```

1. **Bus Interface Unit (BIU):** Handles external bus communication, fetches instruction code into a 6-byte FIFO queue, and computes 20-bit physical addresses using segment registers (`CS`, `DS`, `SS`, `ES`) and `IP`.
2. **Execution Unit (EU):** Receives prefetched opcodes from queue, decodes micro-instructions, executes operations using the 16-bit ALU, and updates general registers and 9 active flag bits.

---

### Q2. Explain the programmer's model of 8086, listing all registers and their functions.

1. **Data Registers (16-bit / 8-bit split):**
   - `AX` (`AH/AL`): Accumulator (used in multiplication, division, I/O).
   - `BX` (`BH/BL`): Base register (holds memory base address).
   - `CX` (`CH/CL`): Count register (loop counter, shift count).
   - `DX` (`DH/DL`): Data register (I/O port addressing, high-word math).
2. **Pointer & Index Registers:**
   - `SP` (Stack Pointer), `BP` (Base Pointer), `SI` (Source Index), `DI` (Destination Index).
3. **Segment Registers:**
   - `CS` (Code Segment), `DS` (Data Segment), `SS` (Stack Segment), `ES` (Extra Segment).
4. **Instruction Pointer & Flags:**
   - `IP` (Instruction Pointer), `FLAGS` (9 active flags: `CF`, `PF`, `AF`, `ZF`, `SF`, `TF`, `IF`, `DF`, `OF`).

---

### Q3. Draw and explain the functional pin diagram of 8086 in detail.

- **40-Pin DIP Package Configuration:**
  - `AD0 - AD15` (Pins 2-16, 39): Multiplexed Address/Data Bus.
  - `A16/S3 - A19/S6` (Pins 35-38): Multiplexed Address/Status Bus.
  - `BHE/S7` (Pin 34): Bus High Enable / Status S7.
  - `RD` (Pin 32): Read control output.
  - `READY` (Pin 22): Wait state insertion signal from memory.
  - `INTR` & `NMI` (Pins 17, 18): Interrupt request inputs.
  - `RESET` (Pin 21): System reset input.
  - `MN/MX` (Pin 33): Minimum / Maximum mode select pin.

---

### Q4. Explain memory segmentation and physical address calculation in 8086 with an example.

#### Physical Address Formula
$$\text{Physical Address} = (\text{Segment Register Value} \times 10\text{H}) + \text{Offset Register Value}$$

#### Numerical Example
- **Given:** Code Segment `CS = 2500H`, Instruction Pointer `IP = 0124H`.
- **Calculation:**
  $$\text{CS Value in Hex} = 2500\text{H}$$
  $$\text{Shifted Segment Base } (\text{CS} \times 10\text{H}) = 25000\text{H}$$
  $$\text{Physical Address} = 25000\text{H} + 0124\text{H} = \mathbf{25124\text{H}}$$
- **Result:** The 20-bit address generated on the physical address bus is `25124H`.

---

### Q5. Explain the functioning of 8086 in minimum mode with a diagram.

```
+----------------+  ALE  +------------------+ -> A0 - A19 Address Bus
| 8086 CPU       | ----> | Latches (74LS373)|
| (MN/MX = +5V)  |       +------------------+
|                | AD0-AD15 +---------------+ -> D0 - D15 Data Bus
|                | -------> | Transceivers  |
|                |          +---------------+
|                | Control  +---------------+
|                | -------> | Memory / I/O  |
+----------------+ (RD,WR)  +---------------+
```
- In Minimum Mode ($\text{MN}/\overline{\text{MX}} = 1$), the 8086 operates as a standalone processor.
- Control signals (`RD`, `WR`, `M/IO`, `ALE`, `DT/R`, `DEN`) are generated directly by the 8086 CPU pins without external bus controllers.

---

### Q6. Explain the functioning of 8086 in maximum mode with a diagram.

```
+----------------+  S0,S1,S2 +--------------------+ -> System Control Signals
| 8086 CPU       | --------> | 8288 BUS           |    (MRDC, MWTC, AMWC,
| (MN/MX = GND)  |           | CONTROLLER         |     IORC, IOWC, INTA)
+----------------+           +--------------------+
```
- In Maximum Mode ($\text{MN}/\overline{\text{MX}} = 0$), status outputs $\bar{S}_0, \bar{S}_1, \bar{S}_2$ are sent to an external **Intel 8288 Bus Controller**.
- The 8288 decodes these status lines to generate system memory and I/O command control signals, allowing multi-processor or co-processor (8087 NDP) operation.

---

### Q7. Draw and explain the timing diagram for a read operation in minimum mode.

```
Clock Cycles :    T1    |    T2    |    T3    |    T4    |
CLK          : --__--__--__--__--__--__--__--__--__--__--
A16-A19      : == Address ======== Status ===============
AD0-AD15     : == Address ======== High-Z ===== Data ====
ALE          : --___-------------------------------------
RD           : ---------____________________-------------
DT/R         : _____-------------------------------------
```
- **T1:** `ALE` goes HIGH; 20-bit address output on `AD0-AD15` and `A16-A19`.
- **T2:** `ALE` goes LOW; `AD0-AD15` enters High-Z mode; `RD` signal drops LOW.
- **T3:** Memory places valid data on data bus `AD0-AD15`.
- **T4:** `RD` returns HIGH; CPU latches data into destination register.

---

### Q8. Draw and explain the timing diagram for a write operation in minimum mode.

```
Clock Cycles :    T1    |    T2    |    T3    |    T4    |
CLK          : --__--__--__--__--__--__--__--__--__--__--
A16-A19      : == Address ======== Status ===============
AD0-AD15     : == Address ======== Write Data ===========
ALE          : --___-------------------------------------
WR           : ---------____________________-------------
DT/R         : ------------------------------------------
```
- **T1:** `ALE` goes HIGH; target address output on `AD0-AD15`.
- **T2:** CPU outputs valid write data onto `AD0-AD15` and drops `WR` line LOW.
- **T3:** Data remains stable on data bus; memory writes data into RAM address.
- **T4:** `WR` returns HIGH; bus returns to idle state.

---

### Q9. Explain interrupt structure and interrupt servicing in 8086.

1. **Interrupt Types:**
   - **Hardware Interrupts:** External pin signals — Non-Maskable Interrupt (`NMI`, Type 2) and Maskable Interrupt (`INTR`).
   - **Software Interrupts:** Triggered by instructions — `INT n` (Type 0-255), `INTO` (Overflow), `INT 3` (Breakpoint).
2. **Interrupt Vector Table (IVT):**
   - Located at memory range `00000H` to `003FFH` (1KB size).
   - Contains 256 vector pointers (4 bytes per vector: 2 bytes `IP` + 2 bytes `CS`).
3. **Servicing Sequence:**
   - Push `FLAGS`, clear `IF` and `TF`, push `CS`, push `IP`.
   - Read vector address `4 * Type Number`, load `CS:IP`, and jump to ISR.
"""

u3_10m = """# 10-Mark Questions & Answers — MPCA Unit 3: The Intel Microprocessor 8086 Architecture

---

### Q1. Explain the internal architecture of 8086 in detail (BIU, EU, registers, flag register) with a neat labeled diagram.

```
+-----------------------------------------------------------------------------------+
|                            BUS INTERFACE UNIT (BIU)                               |
|                                                                                   |
|  Segment Registers:   [ CS: Code ] [ DS: Data ] [ SS: Stack ] [ ES: Extra ]       |
|                       Instruction Pointer: [ IP ]                                 |
|                                   |                                               |
|                                   v                                               |
|                       20-Bit Physical Address Generator Adder                     |
|                                   |                                               |
|                                   v                                               |
|                   6-Byte Instruction Queue  [ Q1 | Q2 | Q3 | Q4 | Q5 | Q6 ]          |
+-----------------------------------|-----------------------------------------------+
                                    | Internal System Bus
+-----------------------------------|-----------------------------------------------+
|                            EXECUTION UNIT (EU)                                    |
|                                                                                   |
|  General Registers:   [ AH | AL ] (AX)   [ BH | BL ] (BX)                         |
|                       [ CH | CL ] (CX)   [ DH | DL ] (DX)                         |
|  Pointers & Indexes:  [ SP: Stack Ptr ]  [ BP: Base Ptr ]                         |
|                       [ SI: Src Index ]  [ DI: Dest Index ]                       |
|                                                                                   |
|  Control Logic <---> 16-Bit ALU <---> 16-Bit Flag Register                        |
|                                       [O|D|I|T|S|Z|A|P|C]                         |
+-----------------------------------------------------------------------------------+
```

#### 1. Bus Interface Unit (BIU)
- **Segment Registers:** Four 16-bit registers (`CS`, `DS`, `SS`, `ES`) storing segment base addresses.
- **Instruction Pointer (IP):** Holds the 16-bit offset of the next instruction byte to fetch.
- **Instruction Queue:** 6-byte FIFO buffer prefetching instructions during idle memory cycles.

#### 2. Execution Unit (EU)
- **ALU (16-bit):** Performs arithmetic and bitwise logic operations.
- **General Purpose Registers:** `AX` (Accumulator), `BX` (Base), `CX` (Counter), `DX` (Data).
- **Pointer/Index Registers:** `SP`, `BP`, `SI`, `DI`.
- **16-bit Flag Register (9 Active Flags):**
  - **Status Flags:** `CF` (Carry), `PF` (Parity), `AF` (Aux Carry), `ZF` (Zero), `SF` (Sign), `OF` (Overflow).
  - **Control Flags:** `IF` (Interrupt Enable), `DF` (Direction Flag), `TF` (Trap Flag).

---

### Q2. Explain the functional pin diagram of 8086 microprocessor in detail, describing the function of each pin group (address/data bus, control signals, power supply).

```
                      +---  --- +
                 GND  | 1    40 | VCC (+5V)
             AD14 <-> | 2    39 | <-> AD15
             AD13 <-> | 3    38 | -> A16/S3
             AD12 <-> | 4    37 | -> A17/S4
             AD11 <-> | 5    36 | -> A18/S5
             AD10 <-> | 6    37 | -> A19/S6
              AD9 <-> | 7    34 | -> BHE/S7
              AD8 <-> | 8    33 | -> MN/MX
              AD7 <-> | 9    32 | -> RD
              AD6 <-> | 10   31 | -> HOLD (RQ/GT0)
              AD5 <-> | 11   30 | -> HLDA (RQ/GT1)
              AD4 <-> | 12   29 | -> WR (LOCK)
              AD3 <-> | 13   28 | -> M/IO (S2)
              AD2 <-> | 14   27 | -> DT/R (S1)
              AD1 <-> | 15   26 | -> DEN (S0)
              AD0 <-> | 16   25 | -> ALE (QS0)
              NMI --> | 17   24 | -> INTA (QS1)
             INTR --> | 18   23 | <- TEST
              CLK --> | 19   22 | <- READY
              GND     | 20   21 | --> RESET
                      +--------+
```

1. **Multiplexed Address/Data Bus ($\text{AD}_0 - \text{AD}_{15}$):** Time-multiplexed lines carrying lower 16-bit memory address during $T_1$ and 16-bit data during $T_2-T_4$.
2. **Address/Status Lines ($\text{A}_{16}/\text{S}_3 - \text{A}_{19}/\text{S}_6$):** Upper 4-bit address lines multiplexed with CPU status indicators.
3. **Minimum Mode Control Signals:**
   - `ALE` (Address Latch Enable), `RD`, `WR`, `M/IO`, `DT/R`, `DEN`, `INTA`.
4. **Maximum Mode Status Lines:**
   - $\bar{S}_0, \bar{S}_1, \bar{S}_2$ decoded by 8288 bus controller into memory/IO read-write commands.
5. **System Controls & Power:** `VCC` (+5V), `GND`, `CLK` (Clock input 5-10MHz), `RESET`, `READY`, `NMI`, `INTR`.

---

### Q3. Explain memory segmentation and banking in 8086 in detail with physical address calculation examples. Also explain why segmentation is used.

#### 1. Why Memory Segmentation is Used
- Allows a 16-bit CPU architecture with 16-bit registers to address **1MB ($2^{20}$ bytes)** of physical memory.
- Enables modular code relocation and dynamic memory protection between code, data, and stack spaces.

#### 2. Physical Address Calculation Formula & Example
$$\text{Physical Address} = (\text{Segment Register} \times 16_{10}) + \text{Offset}$$

- **Example 1 (Instruction Fetch):** `CS = 3000H`, `IP = 0100H`
  $$\text{PA} = (3000\text{H} \times 10\text{H}) + 0100\text{H} = 30000\text{H} + 0100\text{H} = \mathbf{30100\text{H}}$$
- **Example 2 (Data Read):** `DS = 4500H`, `BX = 0250H`
  $$\text{PA} = (4500\text{H} \times 10\text{H}) + 0250\text{H} = 45000\text{H} + 0250\text{H} = \mathbf{45250\text{H}}$$

#### 3. Memory Banking System (Even & Odd Banks)

```
        1MB PHYSICAL MEMORY SYSTEM
       /                          \
 EVEN BANK (512 KB)           ODD BANK (512 KB)
 Address Line A0 = 0          Bus High Enable BHE = 0
 Data Bus D0 - D7             Data Bus D8 - D15
```

---

### Q4. Explain the functioning of 8086 in both minimum mode and maximum mode with neat diagrams, and state the key differences.

#### 1. Minimum Mode Block Diagram ($\text{MN}/\overline{\text{MX}} = 1$)

```
+-----------+  ALE  +-----------+ -> 20-bit Address Bus
| 8086 CPU  | ----->| 74LS373   |
| (MN/MX=1) |       +-----------+
|           | AD0-15+-----------+ -> 16-bit Data Bus
|           | ----->| 74LS245   |
|           |       +-----------+
|           |Control+-----------+ -> Memory/IO Controls (RD, WR, M/IO)
+-----------+ ----->| Memory/IO |
                    +-----------+
```

#### 2. Maximum Mode Block Diagram ($\text{MN}/\overline{\text{MX}} = 0$)

```
+-----------+ S0,S1,S2 +------------+ -> Control Signals (MRDC, MWTC, IORC, IOWC)
| 8086 CPU  | -------->| 8288 BUS   |
| (MN/MX=0) |          | CONTROLLER |
+-----------+          +------------+
```

---

### Q5. Draw and explain in detail the timing diagrams for read and write operations in both minimum and maximum mode of 8086.

```
MINIMUM MODE READ TIMING DIAGRAM:

CLK     : __--__--__--__--__--__--__--__--__--
          |   T1   |   T2   |   T3   |   T4   |
ALE     : --____------------------------------
A16-A19 : == Address ====== Status ===========
AD0-AD15: == Address ====== High-Z === Data ==
RD      : ---------___________________--------
```

---

### Q6. Explain the interrupt structure of 8086 in detail, including types of interrupts (hardware/software), interrupt vector table, and interrupt servicing procedure.

```
INTERRUPT VECTOR TABLE (00000H - 003FFH, 1KB RAM)
+------------------------------------+ 003FFH
| Vector 255 (Type 255)              |
| ...                                |
| Vector 2 (NMI - Non-Maskable Pin)  |
| Vector 1 (Single Step / Trap)      |
| Vector 0 (Divide-by-Zero Error)    |
+------------------------------------+ 00000H
```

---

### Q7. Explain the process of demultiplexing the address/data bus in 8086 with a circuit diagram (using latch 74LS373).

```
                 +-----------------------+
                 | 8086 MICROPROCESSOR   |
                 +-----------------------+
                   | AD0-AD15     | ALE
                   v              v
            +--------------+  +-------+
            | 74LS373      |<-| LATCH |
            | OCTAL LATCH  |  | EN    |
            +--------------+  +-------+
             /            \
            v              v
   A0 - A15 Address Bus   D0 - D15 Data Bus
```
"""

# Write Unit 3 files
with open(os.path.join(unit3_dir, "2M.md"), "w", encoding="utf-8") as f: f.write(u3_2m)
with open(os.path.join(unit3_dir, "3M.md"), "w", encoding="utf-8") as f: f.write(u3_3m)
with open(os.path.join(unit3_dir, "5M.md"), "w", encoding="utf-8") as f: f.write(u3_5m)
with open(os.path.join(unit3_dir, "10M.md"), "w", encoding="utf-8") as f: f.write(u3_10m)

print("Created Unit 3 QA Files!")
