import os

MPCA_DIR = r"S:\B.Tech Data Science Notes\Semester 3\MPCA"

unit2_dir = os.path.join(MPCA_DIR, "Module 2", "Module_2_QA")
unit3_dir = os.path.join(MPCA_DIR, "Module 3", "Module_3_QA")

# --------------------------------------------------------------------------
# UNIT 2 REWRITE
# --------------------------------------------------------------------------
u2_2m = """# 2-Mark Questions & Answers — MPCA Unit 2: Processor Organization & Architecture

---

### Q1. Define pipelining.

**Pipelining** is an instruction execution technique where multiple instructions are overlapped in execution across independent hardware stages (Fetch, Decode, Execute, Memory, Write-back), increasing instruction throughput without increasing individual execution time.

---

### Q2. What is a pipeline hazard?

A **Pipeline Hazard** is any condition or situation (such as structural resource contention, data dependencies, or branch instructions) that prevents the next instruction in the pipeline stream from executing in its designated clock cycle.

---

### Q3. List Flynn's classification of computer architecture.

1. **SISD:** Single Instruction Stream, Single Data Stream.
2. **SIMD:** Single Instruction Stream, Multiple Data Streams.
3. **MISD:** Multiple Instruction Streams, Single Data Stream.
4. **MIMD:** Multiple Instruction Streams, Multiple Data Streams.

---

### Q4. What is microprogrammed control unit?

A **Microprogrammed Control Unit** is a control unit design where control signals are generated by reading microinstructions (stored in a Control Memory ROM) sequentially, rather than using fixed hardwired logic gates.

---

### Q5. Define instruction cycle.

An **Instruction Cycle** (or Fetch-Decode-Execute cycle) is the sequence of operations performed by the CPU to execute a single machine instruction. It consists of the **Fetch phase**, **Decode phase**, **Effective Address calculation phase**, **Execute phase**, and **Interrupt service check phase**.
"""

u2_3m = """# 3-Mark Questions & Answers — MPCA Unit 2: Processor Organization & Architecture

---

### Q1. Explain the basic instruction cycle with interrupt processing.

```
+---------------+     +----------------+     +-----------------+
| FETCH         | --> | DECODE         | --> | EXECUTE         |
| Instruction   |     | Instruction    |     | Operation       |
+---------------+     +----------------+     +-----------------+
        ^                                             |
        |               [Interrupt Pending?]          v
        +------------------ NO <--- [CHECK INTERRUPT]
                                         | YES
                                         v
                              +--------------------+
                              | SAVE CONTEXT (PC)  |
                              | & JUMP TO ISR      |
                              +--------------------+
```
- **Fetch:** Load instruction from memory (`PC` -> `MAR` -> `RAM` -> `IR`).
- **Decode:** Decode opcode and fetch required operands.
- **Execute:** Perform operation in ALU.
- **Interrupt Check:** Check if a hardware/software interrupt flag is set; if yes, push context to stack and jump to Interrupt Service Routine (ISR).

---

### Q2. Differentiate between hardwired and microprogrammed control unit.

| Feature | Hardwired Control Unit | Microprogrammed Control Unit |
| :--- | :--- | :--- |
| **Implementation** | Fixed logic gates, flip-flops, decoders. | Microcode software stored in Control Memory (ROM). |
| **Speed** | Very Fast (hardware gate speeds). | Slower (requires ROM access cycles). |
| **Flexibility / Modifiability** | Rigid; hard to modify or update. | Flexible; easy to update microcode. |
| **Cost & Design** | Complex design, costly for complex ISA. | Systematic design, cheaper for CISC. |

---

### Q3. Explain types of pipeline hazards (structural, data, control) briefly.

1. **Structural Hazard (Resource Conflict):** Occurs when two instructions in different stages attempt to access the same physical hardware resource simultaneously (e.g., single memory port for instruction fetch and data read).
2. **Data Hazard (Data Dependency):** Occurs when an instruction depends on the result of a previous instruction that has not yet completed execution (RAW, WAR, WAW hazards).
3. **Control Hazard (Branch Hazard):** Occurs due to conditional or unconditional branch instructions that alter the sequential flow of the Program Counter (`PC`).

---

### Q4. Explain Flynn's classification (SISD, SIMD, MISD, MIMD) with examples.

1. **SISD (Single Instruction, Single Data):** Classic single-core processor executing one stream of scalar data (e.g., Intel 8086, traditional single-core CPUs).
2. **SIMD (Single Instruction, Multiple Data):** One instruction operates on vector/matrix array elements concurrently (e.g., GPUs, Intel AVX/SSE).
3. **MISD (Multiple Instruction, Single Data):** Multiple processors execute different instructions on the same data stream (e.g., Space Shuttle fault-tolerant flight control).
4. **MIMD (Multiple Instruction, Multiple Data):** Independent processors executing different instructions on independent data streams (e.g., Intel Core i9 multi-core CPUs, supercomputers).

---

### Q5. What are micro-operations? Give examples.

**Micro-operations** are elementary functional operations executed by CPU hardware during a single clock pulse to perform register transfers, ALU calculations, or bus reads.
- **Examples:**
  1. `MAR <- PC` (Transfer Program Counter to Memory Address Register)
  2. `DR <- M[MAR]` (Fetch memory contents into Data Register)
  3. `PC <- PC + 1` (Increment Program Counter)
  4. `AC <- AC + DR` (Add Data Register to Accumulator)
"""

u2_5m = """# 5-Mark Questions & Answers — MPCA Unit 2: Processor Organization & Architecture

---

### Q1. Explain hardwired control unit design with a block diagram.

```
                +---------------------------------------+
                |  INSTRUCTION REGISTER (IR) (Opcode)  |
                +---------------------------------------+
                                   |
                                   v
+---------------+        +--------------------+        +---------------------+
| CLOCK PULSES  | -----> | INSTRUCTION DECODER| <----- | SEQUENCE COUNTER    |
+---------------+        +--------------------+        | & FLAG CONDITIONERS |
                                   |                   +---------------------+
                                   v
                        +----------------------+
                        | CONTROL LOGIC GATES  |
                        +----------------------+
                                   |
                                   v
                     System Control Signals (Read, Write, ALU Control)
```

1. **Opcode Decoder:** Decodes machine instruction opcode into active signal lines.
2. **Sequence Counter:** Generates timing signals (`T0, T1, T2, ...`) for sequential step execution.
3. **Control Logic Combinational Circuit:** Logic gates synthesize control signals (`C_read`, `C_write`, `ALU_add`) dynamically based on opcode and condition flags.
4. **Pros & Cons:** Ultra-high speed execution, but extremely difficult to modify or debug once fabricated.

---

### Q2. Explain microprogrammed control unit with microinstruction sequencing and execution.

```
+------------------+     +------------------------+     +------------------------+
| NEXT ADDRESS     | --> | CONTROL MEMORY (ROM)   | --> | CONTROL ADDRESS        |
| GENERATOR        |     | (Microprogram Storage) |     | REGISTER (CAR)         |
+------------------+     +------------------------+     +------------------------+
         ^                                                          |
         |                   +------------------+                   v
         +------------------ | CONTROL DATA     | --------> Control Signals
                             | REGISTER (CDR)   |           to CPU Hardware
                             +------------------+
```

1. **Control Memory (ROM):** Holds sequences of microinstructions (microprogram) for every machine instruction opcode.
2. **Control Address Register (CAR):** Contains the memory address of the next microinstruction to fetch.
3. **Control Data Register (CDR) / Control Buffer:** Holds the currently fetched microinstruction containing control signals and next-address fields.
4. **Sequencing & Execution:**
   - **Sequencer Logic:** Determines whether to increment `CAR` or branch to a target microinstruction address based on condition flags.

---

### Q3. Explain instruction pipelining with a diagram and discuss speedup achieved.

```
Clock Cycle  :  C1    C2    C3    C4    C5    C6    C7
------------------------------------------------------
Instr 1      : [ IF ][ ID ][ EX ][ MEM ][ WB ]
Instr 2      :       [ IF ][ ID ][ EX  ][ MEM ][ WB ]
Instr 3      :             [ IF ][ ID  ][ EX  ][ MEM ][ WB ]
```

#### Speedup Calculation
For a **k-stage pipeline** executing **n instructions**:
- **Non-Pipelined Time:** `T_non_pipe = n × k × τ`
- **Pipelined Time:** `T_pipe = (k + n - 1) × τ`
- **Speedup Ratio (S):**
  ```
  Speedup (S) = T_non_pipe / T_pipe = (n × k × τ) / [ (k + n - 1) × τ ]
  ```
- For a large number of instructions (`n -> ∞`):
  ```
  Maximum Speedup (S_max) = k  (Equal to number of pipeline stages)
  ```

---

### Q4. Explain different types of pipeline hazards and techniques to overcome them.

1. **Structural Hazards (Hardware Conflicts):**
   - *Cause:* Multiple stages attempting simultaneous access to a shared resource.
   - *Solution:* Duplicate resources (e.g., separate Instruction Cache and Data Cache).
2. **Data Hazards (Data Dependencies):**
   - *Types:* Read-After-Write (RAW), Write-After-Read (WAR), Write-After-Write (WAW).
   - *Solution:* **Data Forwarding / Bypassing** (routing ALU output directly back to ALU input), or inserting **Pipeline Stalls (NOPs/Bubbles)**.
3. **Control Hazards (Branch Dependencies):**
   - *Cause:* Conditional branch decisions delaying instruction fetch stream.
   - *Solution:* **Branch Prediction** (Static/Dynamic), **Branch Target Buffers (BTB)**, or **Delayed Branching**.

---

### Q5. Describe Flynn's classification of parallel processing architectures in detail with diagrams.

```
       +----------------------------------+----------------------------------+
       |            SINGLE DATA           |          MULTIPLE DATA           |
+------+----------------------------------+----------------------------------+
|SINGLE|  SISD (Single Inst, Single Data)  |  SIMD (Single Inst, Multiple Data)|
|INST  |  [CU] -> [PE] -> [Memory]        |  [CU] -> [PE1, PE2, PE3]         |
+------+----------------------------------+----------------------------------+
|MULTI |  MISD (Multi Inst, Single Data)  |  MIMD (Multi Inst, Multiple Data)|
|INST  |  [CU1, CU2] -> [Single Data]     |  [CU1, CU2] -> [PE1, PE2]        |
+------+----------------------------------+----------------------------------+
```

1. **SISD:** Standard uniprocessor system.
2. **SIMD:** Vector processors, GPUs, SIMD extensions (AVX-512) for parallel array calculations.
3. **MISD:** Specialized fault-tolerant computers (redundant processing on identical data).
4. **MIMD:** Multi-core processors, distributed computing clusters, supercomputers.

---

### Q6. Explain the basic instruction cycle along with interrupt processing in detail.

1. **Fetch Phase:** CPU fetches opcode byte from memory location specified by `PC` into `IR`. Program Counter is incremented (`PC = PC + 1`).
2. **Decode Phase:** Control unit decodes opcode to determine operation and operand locations.
3. **Operand Fetch Phase:** Effective address is calculated and operands loaded into data registers.
4. **Execute Phase:** ALU performs arithmetic or logical operation.
5. **Interrupt Processing Phase:**
   - At the end of every instruction cycle, the CPU polls the Interrupt request line.
   - If an interrupt is active and enabled:
     1. Current `PC` and `FLAGS` are pushed onto the Stack.
     2. Interrupt vector address is loaded into `PC`.
     3. Execution jumps to the Interrupt Service Routine (ISR).
     4. `IRET` pops saved state back to resume original program execution.
"""

u2_10m = """# 10-Mark Questions & Answers — MPCA Unit 2: Processor Organization & Architecture

---

### Q1. Explain hardwired and microprogrammed control units in detail with block diagrams, and compare their advantages/disadvantages.

#### 1. Hardwired Control Unit Architecture

```
                       +-------------------------------+
                       | INSTRUCTION REGISTER (IR)     |
                       +-------------------------------+
                                       |
                                       v
+------------------+         +-------------------+         +-----------------------+
| SYSTEM CLOCK     | ------->| OPCODE DECODER    | <-------| SEQUENCE COUNTER      |
+------------------+         +-------------------+         | & CONDITION FLAGS     |
                                       |                   +-----------------------+
                                       v
                            +----------------------+
                            | COMBINATIONAL LOGIC  |
                            | MATRIX (Gates)       |
                            +----------------------+
                                       |
                                       v
                            Control Signals (Read/Write/ALU)
```

#### 2. Microprogrammed Control Unit Architecture

```
+---------------------+     +-----------------------+     +----------------------+
| CONTROL ADDRESS     | --> | CONTROL MEMORY (ROM)  | --> | CONTROL DATA REGISTER|
| REGISTER (CAR)      |     | (Microcode Storage)   |     | (CDR / Microinst)    |
+---------------------+     +-----------------------+     +----------------------+
           ^                                                         |
           |                  +---------------------+                v
           +----------------- | SEQUENCER LOGIC     | <---- Control Signals to Hardware
                              +---------------------+
```

#### 3. Comprehensive Comparison Table

| Feature | Hardwired Control Unit | Microprogrammed Control Unit |
| :--- | :--- | :--- |
| **Logic Implementation** | Fixed combinational logic gates & flip-flops. | Microcode software stored in Control Memory ROM. |
| **Execution Speed** | Extremely fast (limited only by hardware gate delay). | Slower (dependent on Control ROM fetch cycle time). |
| **Flexibility** | Rigid. Modifications require hardware redesign. | Highly flexible. Upgraded by updating Control ROM microcode. |
| **Instruction Set Type** | Best suited for RISC architectures. | Best suited for complex CISC architectures. |
| **Cost & Complexity** | High cost and design complexity for large ISAs. | Systematic design, lower cost for complex ISAs. |
| **Debugging & Maintenance**| Difficult to debug and maintain. | Easier to debug and maintain. |

---

### Q2. Explain instruction pipelining in detail. Discuss structural, data, and control hazards with examples and methods to resolve each (forwarding, stalling, branch prediction).

#### 1. 5-Stage RISC Instruction Pipeline

```
Stage 1: IF  (Instruction Fetch)   -> Read instruction from I-Cache.
Stage 2: ID  (Instruction Decode)  -> Read registers & decode instruction.
Stage 3: EX  (Execution / ALU)     -> Execute ALU operation or calculate memory address.
Stage 4: MEM (Memory Access)       -> Read/Write data from D-Cache.
Stage 5: WB  (Write Back)          -> Write result back into destination register.
```

#### 2. Pipeline Hazards & Resolution Strategies

1. **Structural Hazards (Resource Contention):**
   - *Example:* A single-port memory attempting simultaneous instruction fetch (`IF`) and data memory read (`MEM`).
   - *Resolution:* Implement separate Instruction and Data Caches (Harvard Architecture model).

2. **Data Hazards (Data Dependencies):**
   - *Example (RAW Hazard):*
     ```assembly
     ADD R1, R2, R3   ; R1 written in WB stage
     SUB R4, R1, R5   ; R1 read in ID stage (Hazard!)
     ```
   - *Resolution Methods:*
     - **Data Forwarding (Bypassing):** Connect the ALU output of `EX` stage directly back to `EX` stage input via a multiplexer, eliminating wait cycles.
     - **Pipeline Stalling (NOPs / Bubbles):** Insert hardware stall cycles until data is written back.

3. **Control Hazards (Branch Dependencies):**
   - *Example:* Conditional branch instruction `BEQ R1, R2, Target` alters sequential instruction fetching.
   - *Resolution Methods:*
     - **Static/Dynamic Branch Prediction:** Predict whether branch is taken or not taken (Branch History Table).
     - **Branch Target Buffer (BTB):** Cache branch target addresses for instant fetching.

---

### Q3. Explain the basic instruction cycle with interrupt processing in detail, including the fetch-decode-execute cycle and interrupt handling mechanism.

```
                      +-------------------+
                      |   FETCH STAGE     |
                      |   MAR <- PC       |
                      |   MDR <- M[MAR]   |
                      |   IR  <- MDR      |
                      |   PC  <- PC + 1   |
                      +-------------------+
                                |
                                v
                      +-------------------+
                      |   DECODE STAGE    |
                      |   Decode Opcode   |
                      |   Fetch Operands  |
                      +-------------------+
                                |
                                v
                      +-------------------+
                      |   EXECUTE STAGE   |
                      |   ALU Compute     |
                      |   Write Result    |
                      +-------------------+
                                |
                                v
                      +-------------------+
                      | INTERRUPT CHECK?  |
                      +-------------------+
                         /             \
                   YES  /               \ NO
                       v                 v
            +--------------------+    Next Cycle (Fetch)
            | Push PC & FLAGS    |
            | Load ISR Address   |
            +--------------------+
```

---

### Q4. Describe microinstruction sequencing and execution techniques (in microprogrammed control) along with a suitable example of microinstruction format.

#### 1. Microinstruction Format Structure

```
+-------------------+--------------------+--------------------+--------------------+
| CONTROL FIELD     | CONDITION FIELD    | BRANCH FIELD       | ADDRESS FIELD      |
| (Control Signals) | (Status Flags Test)| (Jump Condition)   | (Next Micro-Addr)  |
| (16-32 bits)      | (2-4 bits)         | (2-3 bits)         | (8-12 bits)        |
+-------------------+--------------------+--------------------+--------------------+
```

---

### Q5. Explain Flynn's classification of computer architectures in detail with block diagrams and real-world examples for each category.

```
1. SISD Architecture                  2. SIMD Architecture
   +----+     +----+     +------+        +----+     +-----+ -> [PE1] -> [Mem1]
   | CU | --> | PE | --> | Mem  |        | CU | --> | Bus | -> [PE2] -> [Mem2]
   +----+     +----+     +------+        +----+     +-----+ -> [PE3] -> [Mem3]

3. MISD Architecture                  4. MIMD Architecture
   +-----+     +-----+                   +-----+     +-----+     +------+
   | CU1 | --> | PE1 | -\                | CU1 | --> | PE1 | --> | Mem1 |
   +-----+     +-----+   \               +-----+     +-----+     +------+
                          +-> [Shared]
   +-----+     +-----+   /               +-----+     +-----+     +------+
   | CU2 | --> | PE2 | -/                | CU2 | --> | PE2 | --> | Mem2 |
   +-----+     +-----+                   +-----+     +-----+     +------+
```
"""

# Write Unit 2 files
with open(os.path.join(unit2_dir, "2M.md"), "w", encoding="utf-8") as f: f.write(u2_2m)
with open(os.path.join(unit2_dir, "3M.md"), "w", encoding="utf-8") as f: f.write(u2_3m)
with open(os.path.join(unit2_dir, "5M.md"), "w", encoding="utf-8") as f: f.write(u2_5m)
with open(os.path.join(unit2_dir, "10M.md"), "w", encoding="utf-8") as f: f.write(u2_10m)

# --------------------------------------------------------------------------
# UNIT 3 REWRITE
# --------------------------------------------------------------------------
u3_2m = """# 2-Mark Questions & Answers — MPCA Unit 3: The Intel Microprocessor 8086 Architecture

---

### Q1. List the functional units of the 8086 microprocessor.

The 8086 CPU is divided into two independent functional units:
1. **Bus Interface Unit (BIU):** Manages instruction prefetching, memory bus communication, segment registers, and physical address generation.
2. **Execution Unit (EU):** Decodes micro-instructions, executes arithmetic/logical operations in ALU, and manages general-purpose registers and flags.

---

### Q2. What is memory segmentation in 8086?

**Memory Segmentation** is a technique that divides the 1MB physical memory space into 64KB logical blocks called segments (Code Segment, Data Segment, Stack Segment, Extra Segment). It allows a 16-bit processor to address 20-bit physical addresses using segment base registers and offset registers.

---

### Q3. Define minimum mode and maximum mode of 8086.

- **Minimum Mode (MN/MX' = 1):** Single-processor system mode where 8086 generates all bus control signals (`RD`, `WR`, `ALE`, `M/IO`) directly.
- **Maximum Mode (MN/MX' = 0):** Multi-processor system mode where bus control signals are generated by an external Bus Controller chip (Intel 8288).

---

### Q4. What is the purpose of demultiplexing the address/data bus?

The 8086 uses multiplexed pins **AD0 - AD15** to save physical pin count. **Demultiplexing** separates the 20-bit memory address from 16-bit data using octal latches (74LS373) driven by the Address Latch Enable (`ALE`) signal.

---

### Q5. State the size of the 8086 instruction queue.

The 8086 Bus Interface Unit (BIU) contains a **6-byte Instruction Queue** that prefetches instruction bytes sequentially from memory when the EU is busy, enabling instruction pipelined prefetching.
"""

u3_3m = """# 3-Mark Questions & Answers — MPCA Unit 3: The Intel Microprocessor 8086 Architecture

---

### Q1. Draw and explain the functional pin diagram of 8086 (any 6-8 important pins).

1. **AD0 - AD15 (Pins 2-16, 39):** Multiplexed Address/Data lines carrying 16-bit data or lower 16-bit memory address.
2. **A16/S3 - A19/S6 (Pins 35-38):** Multiplexed upper 4-bit address lines and status signals.
3. **ALE (Address Latch Enable):** High pulse indicating valid address is present on multiplexed bus.
4. **RD / WR:** Memory/IO Read and Write control output signals.
5. **MN/MX' (Pin 33):** Configures CPU for Minimum Mode (+5V) or Maximum Mode (GND).
6. **RESET (Pin 21):** Resets CPU; sets `CS = FFFFH`, `IP = 0000H`.

---

### Q2. Explain memory segmentation in 8086 with a diagram.

```
1 MB Memory Space (00000H to FFFFFH)
+------------------------------------+ FFFFFH
|      UNMAPPED MEMORY SPACE         |
+------------------------------------+
|  EXTRA SEGMENT (ES)     (64 KB)    | <- ES:DI
+------------------------------------+
|  STACK SEGMENT (SS)     (64 KB)    | <- SS:SP/BP
+------------------------------------+
|  DATA SEGMENT (DS)      (64 KB)    | <- DS:BX/SI
+------------------------------------+
|  CODE SEGMENT (CS)      (64 KB)    | <- CS:IP
+------------------------------------+ 00000H
```
- Total Physical Address Space = `2^20 = 1 MB`.
- Divided into 4 active 64KB logical segments: **CS** (Code), **DS** (Data), **SS** (Stack), **ES** (Extra).

---

### Q3. Explain the concept of banking (memory banking) in 8086.

```
         1MB PHYSICAL MEMORY
       /                     \
  EVEN BANK (Even Bytes)     ODD BANK (Odd Bytes)
  512 KB (D0 - D7)           512 KB (D8 - D15)
  Connected to A0 = 0        Connected to BHE' = 0
```
- Memory is split into two 512KB banks:
  - **Even Bank (Lower Bank):** Contains even byte addresses (`00000H, 00002H, ...`), driven by `A0 = 0`.
  - **Odd Bank (Upper Bank):** Contains odd byte addresses (`00001H, 00003H, ...`), driven by `BHE' = 0`.
- Enables fetching 16-bit word data in a single memory cycle when aligned on an even address.

---

### Q4. Differentiate between minimum mode and maximum mode operation of 8086.

| Feature | Minimum Mode | Maximum Mode |
| :--- | :--- | :--- |
| **Pin Setup** | Pin 33 (MN/MX') connected to +5V. | Pin 33 (MN/MX') connected to GND. |
| **System Architecture**| Single CPU processor system. | Multi-processor / Co-processor system (8087 FPU, 8089 IOP). |
| **Control Generator** | 8086 directly outputs `RD`, `WR`, `ALE`, `M/IO`. | External 8288 Bus Controller decodes status pins `S0', S1', S2'`. |

---

### Q5. Explain the need for demultiplexing the address/data bus in 8086.

1. Pins **AD0 - AD15** carry memory addresses during the first clock cycle (`T1`) and data during `T2, T3, T4`.
2. Without demultiplexing, memory chips would lose the target address when data values are placed on the pins during `T2`.
3. Latches (74LS373) latch the address when `ALE = 1`, preserving a stable 20-bit address throughout the memory cycle.
"""

u3_5m = """# 5-Mark Questions & Answers — MPCA Unit 3: The Intel Microprocessor 8086 Architecture

---

### Q1. Explain the internal architecture of 8086 (BIU and EU) with a neat diagram.

```
+-------------------------------------------------------------------------+
|                        BUS INTERFACE UNIT (BIU)                         |
|                                                                         |
|   Segment Registers: [ CS ][ DS ][ SS ][ ES ]    IP: [ Instruction Ptr ]|
|                                  |                                      |
|                                  v                                      |
|                        20-Bit Adder (Physical Addr)                     |
|                                  |                                      |
|                                  v                                      |
|                 6-Byte Instruction Stream Queue [Q1|Q2|Q3|Q4|Q5|Q6]      |
+----------------------------------|--------------------------------------+
                                   | Internal Bus
+----------------------------------v--------------------------------------+
|                           EXECUTION UNIT (EU)                           |
|                                                                         |
|   General Registers:  [ AH | AL ] [ BH | BL ] [ CH | CL ] [ DH | DL ]   |
|   Pointers & Indexes: [ SP ] [ BP ] [ SI ] [ DI ]                       |
|                                                                         |
|   Control Logic <---> 16-Bit ALU <---> Status & Control Flags (16-bit)   |
+-------------------------------------------------------------------------+
```

1. **Bus Interface Unit (BIU):** Handles external bus communication, fetches instruction code into a 6-byte FIFO queue, and computes 20-bit physical addresses using segment registers (`CS`, `DS`, `SS`, `ES`) and `IP`.
2. **Execution Unit (EU):** Receives prefetched opcodes from queue, decodes micro-instructions, executes operations using the 16-bit ALU, and updates general registers and 9 active flag bits.

---

### Q2. Explain the programmer's model of 8086, listing all registers and their functions.

1. **Data Registers (16-bit / 8-bit split):**
   - `AX` (`AH/AL`): Accumulator (used in multiplication, division, I/O).
   - `BX` (`BH/BL`): Base register (holds memory base address).
   - `CX` (`CH/CL`): Count register (loop counter, shift count).
   - `DX` (`DH/DL`): Data register (I/O port addressing, high-word math).
2. **Pointer & Index Registers:**
   - `SP` (Stack Pointer), `BP` (Base Pointer), `SI` (Source Index), `DI` (Destination Index).
3. **Segment Registers:**
   - `CS` (Code Segment), `DS` (Data Segment), `SS` (Stack Segment), `ES` (Extra Segment).
4. **Instruction Pointer & Flags:**
   - `IP` (Instruction Pointer), `FLAGS` (9 active flags: `CF`, `PF`, `AF`, `ZF`, `SF`, `TF`, `IF`, `DF`, `OF`).

---

### Q3. Draw and explain the functional pin diagram of 8086 in detail.

- **40-Pin DIP Package Configuration:**
  - `AD0 - AD15` (Pins 2-16, 39): Multiplexed Address/Data Bus.
  - `A16/S3 - A19/S6` (Pins 35-38): Multiplexed Address/Status Bus.
  - `BHE'/S7` (Pin 34): Bus High Enable / Status S7.
  - `RD'` (Pin 32): Read control output.
  - `READY` (Pin 22): Wait state insertion signal from memory.
  - `INTR` & `NMI` (Pins 17, 18): Interrupt request inputs.
  - `RESET` (Pin 21): System reset input.
  - `MN/MX'` (Pin 33): Minimum / Maximum mode select pin.

---

### Q4. Explain memory segmentation and physical address calculation in 8086 with an example.

#### Physical Address Formula
```
Physical Address = (Segment Register Value × 16) + Offset Register Value
```

#### Numerical Example
- **Given:** Code Segment `CS = 2500H`, Instruction Pointer `IP = 0124H`.
- **Calculation:**
  ```
  CS Value in Hex = 2500H
  Shifted Segment Base (CS × 16) = 25000H
  Physical Address = 25000H + 0124H = 25124H
  ```
- **Result:** The 20-bit address generated on the physical address bus is `25124H`.

---

### Q5. Explain the functioning of 8086 in minimum mode with a diagram.

```
+----------------+  ALE  +------------------+ -> A0 - A19 Address Bus
| 8086 CPU       | ----> | Latches (74LS373)|
| (MN/MX' = +5V) |       +------------------+
|                | AD0-AD15 +---------------+ -> D0 - D15 Data Bus
|                | -------> | Transceivers  |
|                |          +---------------+
|                | Control  +---------------+
|                | -------> | Memory / I/O  |
+----------------+ (RD,WR)  +---------------+
```
- In Minimum Mode (`MN/MX' = 1`), the 8086 operates as a standalone processor.
- Control signals (`RD`, `WR`, `M/IO`, `ALE`, `DT/R`, `DEN`) are generated directly by the 8086 CPU pins without external bus controllers.

---

### Q6. Explain the functioning of 8086 in maximum mode with a diagram.

```
+----------------+  S0',S1',S2' +--------------------+ -> System Control Signals
| 8086 CPU       | -----------> | 8288 BUS           |    (MRDC, MWTC, AMWC,
| (MN/MX' = GND) |              | CONTROLLER         |     IORC, IOWC, INTA)
+----------------+              +--------------------+
```
- In Maximum Mode (`MN/MX' = 0`), status outputs `S0', S1', S2'` are sent to an external **Intel 8288 Bus Controller**.
- The 8288 decodes these status lines to generate system memory and I/O command control signals, allowing multi-processor or co-processor (8087 NDP) operation.

---

### Q7. Draw and explain the timing diagram for a read operation in minimum mode.

```
Clock Cycles :    T1    |    T2    |    T3    |    T4    |
CLK          : --__--__--__--__--__--__--__--__--__--__--
A16-A19      : == Address ======== Status ===============
AD0-AD15     : == Address ======== High-Z ===== Data ====
ALE          : --___-------------------------------------
RD           : ---------____________________-------------
DT/R         : _____-------------------------------------
```
- **T1:** `ALE` goes HIGH; 20-bit address output on `AD0-AD15` and `A16-A19`.
- **T2:** `ALE` goes LOW; `AD0-AD15` enters High-Z mode; `RD` signal drops LOW.
- **T3:** Memory places valid data on data bus `AD0-AD15`.
- **T4:** `RD` returns HIGH; CPU latches data into destination register.

---

### Q8. Draw and explain the timing diagram for a write operation in minimum mode.

```
Clock Cycles :    T1    |    T2    |    T3    |    T4    |
CLK          : --__--__--__--__--__--__--__--__--__--__--
A16-A19      : == Address ======== Status ===============
AD0-AD15     : == Address ======== Write Data ===========
ALE          : --___-------------------------------------
WR           : ---------____________________-------------
DT/R         : ------------------------------------------
```
- **T1:** `ALE` goes HIGH; target address output on `AD0-AD15`.
- **T2:** CPU outputs valid write data onto `AD0-AD15` and drops `WR` line LOW.
- **T3:** Data remains stable on data bus; memory writes data into RAM address.
- **T4:** `WR` returns HIGH; bus returns to idle state.

---

### Q9. Explain interrupt structure and interrupt servicing in 8086.

1. **Interrupt Types:**
   - **Hardware Interrupts:** External pin signals — Non-Maskable Interrupt (`NMI`, Type 2) and Maskable Interrupt (`INTR`).
   - **Software Interrupts:** Triggered by instructions — `INT n` (Type 0-255), `INTO` (Overflow), `INT 3` (Breakpoint).
2. **Interrupt Vector Table (IVT):**
   - Located at memory range `00000H` to `003FFH` (1KB size).
   - Contains 256 vector pointers (4 bytes per vector: 2 bytes `IP` + 2 bytes `CS`).
3. **Servicing Sequence:**
   - Push `FLAGS`, clear `IF` and `TF`, push `CS`, push `IP`.
   - Read vector address `4 × Type Number`, load `CS:IP`, and jump to ISR.
"""

u3_10m = """# 10-Mark Questions & Answers — MPCA Unit 3: The Intel Microprocessor 8086 Architecture

---

### Q1. Explain the internal architecture of 8086 in detail (BIU, EU, registers, flag register) with a neat labeled diagram.

```
+-----------------------------------------------------------------------------------+
|                            BUS INTERFACE UNIT (BIU)                               |
|                                                                                   |
|  Segment Registers:   [ CS: Code ] [ DS: Data ] [ SS: Stack ] [ ES: Extra ]       |
|                       Instruction Pointer: [ IP ]                                 |
|                                   |                                               |
|                                   v                                               |
|                       20-Bit Physical Address Generator Adder                     |
|                                   |                                               |
|                                   v                                               |
|                   6-Byte Instruction Queue  [ Q1 | Q2 | Q3 | Q4 | Q5 | Q6 ]          |
+-----------------------------------|-----------------------------------------------+
                                    | Internal System Bus
+-----------------------------------|-----------------------------------------------+
|                            EXECUTION UNIT (EU)                                    |
|                                                                                   |
|  General Registers:   [ AH | AL ] (AX)   [ BH | BL ] (BX)                         |
|                       [ CH | CL ] (CX)   [ DH | DL ] (DX)                         |
|  Pointers & Indexes:  [ SP: Stack Ptr ]  [ BP: Base Ptr ]                         |
|                       [ SI: Src Index ]  [ DI: Dest Index ]                       |
|                                                                                   |
|  Control Logic <---> 16-Bit ALU <---> 16-Bit Flag Register                        |
|                                       [O|D|I|T|S|Z|A|P|C]                         |
+-----------------------------------------------------------------------------------+
```

#### 1. Bus Interface Unit (BIU)
- **Segment Registers:** Four 16-bit registers (`CS`, `DS`, `SS`, `ES`) storing segment base addresses.
- **Instruction Pointer (IP):** Holds the 16-bit offset of the next instruction byte to fetch.
- **Instruction Queue:** 6-byte FIFO buffer prefetching instructions during idle memory cycles.

#### 2. Execution Unit (EU)
- **ALU (16-bit):** Performs arithmetic and bitwise logic operations.
- **General Purpose Registers:** `AX` (Accumulator), `BX` (Base), `CX` (Counter), `DX` (Data).
- **Pointer/Index Registers:** `SP`, `BP`, `SI`, `DI`.
- **16-bit Flag Register (9 Active Flags):**
  - **Status Flags:** `CF` (Carry), `PF` (Parity), `AF` (Aux Carry), `ZF` (Zero), `SF` (Sign), `OF` (Overflow).
  - **Control Flags:** `IF` (Interrupt Enable), `DF` (Direction Flag), `TF` (Trap Flag).

---

### Q2. Explain the functional pin diagram of 8086 microprocessor in detail, describing the function of each pin group (address/data bus, control signals, power supply).

```
                      +---  --- +
                 GND  | 1    40 | VCC (+5V)
             AD14 <-> | 2    39 | <-> AD15
             AD13 <-> | 3    38 | -> A16/S3
             AD12 <-> | 4    37 | -> A17/S4
             AD11 <-> | 5    36 | -> A18/S5
             AD10 <-> | 6    37 | -> A19/S6
              AD9 <-> | 7    34 | -> BHE'/S7
              AD8 <-> | 8    33 | -> MN/MX'
              AD7 <-> | 9    32 | -> RD'
              AD6 <-> | 10   31 | -> HOLD (RQ/GT0')
              AD5 <-> | 11   30 | -> HLDA (RQ/GT1')
              AD4 <-> | 12   29 | -> WR' (LOCK')
              AD3 <-> | 13   28 | -> M/IO' (S2')
              AD2 <-> | 14   27 | -> DT/R' (S1')
              AD1 <-> | 15   26 | -> DEN' (S0')
              AD0 <-> | 16   25 | -> ALE (QS0)
              NMI --> | 17   24 | -> INTA' (QS1)
             INTR --> | 18   23 | <- TEST'
              CLK --> | 19   22 | <- READY
              GND     | 20   21 | --> RESET
                      +--------+
```

1. **Multiplexed Address/Data Bus (AD0 - AD15):** Time-multiplexed lines carrying lower 16-bit memory address during `T1` and 16-bit data during `T2-T4`.
2. **Address/Status Lines (A16/S3 - A19/S6):** Upper 4-bit address lines multiplexed with CPU status indicators.
3. **Minimum Mode Control Signals:**
   - `ALE` (Address Latch Enable), `RD'`, `WR'`, `M/IO'`, `DT/R'`, `DEN'`, `INTA'`.
4. **Maximum Mode Status Lines:**
   - `S0', S1', S2'` decoded by 8288 bus controller into memory/IO read-write commands.
5. **System Controls & Power:** `VCC` (+5V), `GND`, `CLK` (Clock input 5-10MHz), `RESET`, `READY`, `NMI`, `INTR`.

---

### Q3. Explain memory segmentation and banking in 8086 in detail with physical address calculation examples. Also explain why segmentation is used.

#### 1. Why Memory Segmentation is Used
- Allows a 16-bit CPU architecture with 16-bit registers to address **1MB (2^20 bytes)** of physical memory.
- Enables modular code relocation and dynamic memory protection between code, data, and stack spaces.

#### 2. Physical Address Calculation Formula & Example
```
Physical Address = (Segment Register × 16) + Offset
```

- **Example 1 (Instruction Fetch):** `CS = 3000H`, `IP = 0100H`
  ```
  Physical Address = (3000H × 16) + 0100H = 30000H + 0100H = 30100H
  ```
- **Example 2 (Data Read):** `DS = 4500H`, `BX = 0250H`
  ```
  Physical Address = (4500H × 16) + 0250H = 45000H + 0250H = 45250H
  ```

#### 3. Memory Banking System (Even & Odd Banks)

```
        1MB PHYSICAL MEMORY SYSTEM
       /                          \
 EVEN BANK (512 KB)           ODD BANK (512 KB)
 Address Line A0 = 0          Bus High Enable BHE' = 0
 Data Bus D0 - D7             Data Bus D8 - D15
```

---

### Q4. Explain the functioning of 8086 in both minimum mode and maximum mode with neat diagrams, and state the key differences.

#### 1. Minimum Mode Block Diagram (MN/MX' = 1)

```
+-----------+  ALE  +-----------+ -> 20-bit Address Bus
| 8086 CPU  | ----->| 74LS373   |
| (MN/MX=1) |       +-----------+
|           | AD0-15+-----------+ -> 16-bit Data Bus
|           | ----->| 74LS245   |
|           |       +-----------+
|           |Control+-----------+ -> Memory/IO Controls (RD, WR, M/IO)
+-----------+ ----->| Memory/IO |
                    +-----------+
```

#### 2. Maximum Mode Block Diagram (MN/MX' = 0)

```
+-----------+ S0',S1',S2' +------------+ -> Control Signals (MRDC, MWTC, IORC, IOWC)
| 8086 CPU  | ----------->| 8288 BUS   |
| (MN/MX=0) |             | CONTROLLER |
+-----------+             +------------+
```

---

### Q5. Draw and explain in detail the timing diagrams for read and write operations in both minimum and maximum mode of 8086.

```
MINIMUM MODE READ TIMING DIAGRAM:

CLK     : __--__--__--__--__--__--__--__--__--
          |   T1   |   T2   |   T3   |   T4   |
ALE     : --____------------------------------
A16-A19 : == Address ====== Status ===========
AD0-AD15: == Address ====== High-Z === Data ==
RD      : ---------___________________--------
```

---

### Q6. Explain the interrupt structure of 8086 in detail, including types of interrupts (hardware/software), interrupt vector table, and interrupt servicing procedure.

```
INTERRUPT VECTOR TABLE (00000H - 003FFH, 1KB RAM)
+------------------------------------+ 003FFH
| Vector 255 (Type 255)              |
| ...                                |
| Vector 2 (NMI - Non-Maskable Pin)  |
| Vector 1 (Single Step / Trap)      |
| Vector 0 (Divide-by-Zero Error)    |
+------------------------------------+ 00000H
```

---

### Q7. Explain the process of demultiplexing the address/data bus in 8086 with a circuit diagram (using latch 74LS373).

```
                 +-----------------------+
                 | 8086 MICROPROCESSOR   |
                 +-----------------------+
                   | AD0-AD15     | ALE
                   v              v
            +--------------+  +-------+
            | 74LS373      |<-| LATCH |
            | OCTAL LATCH  |  | EN    |
            +--------------+  +-------+
             /            \
            v              v
   A0 - A15 Address Bus   D0 - D15 Data Bus
```
"""

# Write Unit 3 files
with open(os.path.join(unit3_dir, "2M.md"), "w", encoding="utf-8") as f: f.write(u3_2m)
with open(os.path.join(unit3_dir, "3M.md"), "w", encoding="utf-8") as f: f.write(u3_3m)
with open(os.path.join(unit3_dir, "5M.md"), "w", encoding="utf-8") as f: f.write(u3_5m)
with open(os.path.join(unit3_dir, "10M.md"), "w", encoding="utf-8") as f: f.write(u3_10m)

print("Rewrote Unit 2 and Unit 3 QA Files with 100% clean formatting!")
